#baseURL = 'https://example.org/'
#locale = 'en-us'
#title = 'My New Hugo Project'

baseURL = "https://tarekiraki.github.io/"
title = "Tarek Iraki"
theme = "PaperMod"

[params]
  author = "Tarek Iraki"
  description = "AI Researcher and Machine Learning Engineer"
